### ISSUE TITLE
Inquiries about the reproduction of paper results

### ISSUE THREAD

**Issue by c-mengyi** [1ho0jin1/OSFI-by-FineTuning#4]
![image](https://github.com/1ho0jin1/OSFI-by-FineTuning/assets/148559885/e5b9f498-26f7-4d33-8882-d3d3e06b4f28)

ps：The data in black are the experimental results provided in the paper, while the data in red are the results obtained by running your code.

Could you please spare your valuable time to give me some hints about the experimental settings or some possible reasons that makes me unable to reproduce the results?

I really appreciate for your help and look forward to your reply!

**Comment by 1ho0jin1** [comment]
Hi, thanks for your interest in our work!
I checked this issue and found that our previous ```dataset.py``` code does not give the same fold as described in our paper.
Therefore I modified the code so that the known and the unknown identities are kept the same as in our paper.

Below is our reproduced result:
![image](https://github.com/1ho0jin1/OSFI-by-FineTuning/assets/60504706/9aa38fd7-e3d3-4ad8-acc7-455141ea60fe)
Black and red refers to the numbers in the paper and the reproduced results, respectively.

Please update your code to the current version, and change your ```config.py``` to include the paths to known_list.pkl and unknown_list.pkl included in the dataset that we provided.


Hope this helps :)
Feel free to re-open this issue if there is any problem.
